language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
# need "python setup.py install" to install resync so that client tests work
install:
  - sudo apt-get update
  - sudo apt-get install libmagic-dev
  - pip install Pillow iiif_validator
  - python setup.py install
# command to run tests
script:
  - py.test
  - ./run_validate.sh
after_success:
  - coveralls
