language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
# commands to install dependencies
# need "python setup.py install" to install resync so that client tests work
install:
  - sudo apt-get update
  - sudo apt-get install libmagic-dev libwebp-dev
  - pip install Pillow iiif_validator coveralls pep8 pep257 restructuredtext_lint testfixtures
  - python setup.py install
script:
  # use -n with run_validate.sh because I can't get the netpbm tests going on Travis yet
  - ./run_tests.sh
  - ./run_validate.sh -n
after_success:
  # omit the netpbm manipulator from coverage tests because I haven't flashed those out
  - coverage run --source=iiif --omit=iiif/manipulator_netpbm.py setup.py test
  - coveralls
